services :
    mongo:

      image: mongo 
      container_name: mongo_db
      restart: unless-stopped

      ports:
        - "27017:27017"
      
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

      volumes:
        - mongo_data:/data/db
      
      networks:
        - mongo_net

      healthcheck:
        test: ["CMD","mongo" ,"--eval", "db.adminCommand('ping')"]
        interval: 30s
        timeout: 10s
        retries: 5

volumes:
  mongo_data:


networks:
  mongo_net:
  
      
